"""Local SQLite database management for Kovaak Agent.

This module manages all local persistence:
- Settings: key-value user preferences (watch path, provider, model).
- Sources: tracked CSV files with size/mtime signatures to avoid redundant reads.
- Runs: normalized aim-training records parsed from Kovaak's exports.
- Reports: cached AI coaching reports generated by external LLMs.

Operates in SQLite WAL (Write-Ahead Logging) mode for concurrent read/write support.
"""

from __future__ import annotations

import json
import re
import sqlite3
import threading
from datetime import datetime
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator


# Database schema definition:
# - settings: simple key-value store for app configuration.
# - sources: file-level metadata tracking imports, file sizes, timestamps, and error states.
# - runs: normalized aim metrics (score, accuracy, weapon, sensitivity) with raw JSON for auditing.
# - reports: cached LLM coaching digests preserving evidence and provider metadata.
SCHEMA = """
PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sources (
    path TEXT PRIMARY KEY,
    size_bytes INTEGER NOT NULL DEFAULT 0,
    mtime_ns INTEGER NOT NULL DEFAULT 0,
    rows_seen INTEGER NOT NULL DEFAULT 0,
    imported_at TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    error TEXT
);

CREATE TABLE IF NOT EXISTS runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_path TEXT NOT NULL,
    source_row INTEGER NOT NULL,
    row_hash TEXT NOT NULL,
    observed_at TEXT NOT NULL,
    imported_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    scenario TEXT,
    score REAL,
    accuracy REAL,
    duration_seconds REAL,
    shots REAL,
    hits REAL,
    misses REAL,
    damage_done REAL,
    damage_possible REAL,
    efficiency REAL,
    weapon TEXT,
    sensitivity REAL,
    sensitivity_scale TEXT,
    dpi REAL,
    fov REAL,
    fov_scale TEXT,
    avg_fps REAL,
    resolution TEXT,
    game_version TEXT,
    raw_json TEXT NOT NULL,
    UNIQUE(source_path, source_row),
    FOREIGN KEY(source_path) REFERENCES sources(path) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS runs_observed_idx ON runs(observed_at DESC);
CREATE INDEX IF NOT EXISTS runs_scenario_idx ON runs(scenario, observed_at DESC);

CREATE TABLE IF NOT EXISTS reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    kind TEXT NOT NULL,
    provider TEXT,
    model TEXT NOT NULL,
    body TEXT NOT NULL,
    evidence_json TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
"""


# Backward compatibility column migrations:
# When older databases are opened, these column definitions are checked and added if missing.
RUN_COLUMN_MIGRATIONS = {
    "shots": "REAL",
    "hits": "REAL",
    "misses": "REAL",
    "damage_done": "REAL",
    "damage_possible": "REAL",
    "efficiency": "REAL",
    "weapon": "TEXT",
    "sensitivity": "REAL",
    "sensitivity_scale": "TEXT",
    "dpi": "REAL",
    "fov": "REAL",
    "fov_scale": "TEXT",
    "avg_fps": "REAL",
    "resolution": "TEXT",
    "game_version": "TEXT",
}

REPORT_COLUMN_MIGRATIONS = {
    "provider": "TEXT",
}


class Database:
    """Manages SQLite storage, table creation, and queries for runs and reports."""

    def __init__(self, path: str | Path):
        self.path = Path(path)
        self._local = threading.local()
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.initialize()

    @contextmanager
    def connect(self) -> Iterator[sqlite3.Connection]:
        """Context manager yielding a SQLite connection configured with Row factory and auto-commit."""
        current = getattr(self._local, "connection", None)
        if current is not None:
            yield current
            return
        connection = sqlite3.connect(self.path, timeout=10)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")
        self._local.connection = connection
        try:
            yield connection
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            self._local.connection = None
            connection.close()

    def initialize(self) -> None:
        """Create initial tables and apply column migrations for existing databases."""
        with self.connect() as connection:
            connection.executescript(SCHEMA)
            # Add any newly introduced run columns to existing databases
            existing = {row["name"] for row in connection.execute("PRAGMA table_info(runs)").fetchall()}
            for name, column_type in RUN_COLUMN_MIGRATIONS.items():
                if name not in existing:
                    connection.execute(f"ALTER TABLE runs ADD COLUMN {name} {column_type}")
            # Add any newly introduced report columns to existing databases
            existing_reports = {
                row["name"] for row in connection.execute("PRAGMA table_info(reports)").fetchall()
            }
            for name, column_type in REPORT_COLUMN_MIGRATIONS.items():
                if name not in existing_reports:
                    connection.execute(f"ALTER TABLE reports ADD COLUMN {name} {column_type}")
            # History is independent of the current shape or lifetime of a source CSV.
            connection.execute("""CREATE TABLE IF NOT EXISTS run_history (
                event_key TEXT PRIMARY KEY, observed_at TEXT NOT NULL,
                scenario TEXT NOT NULL, payload_json TEXT NOT NULL,
                captured_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)""")
            connection.execute("CREATE INDEX IF NOT EXISTS history_time_idx ON run_history(observed_at)")
            connection.execute("CREATE TABLE IF NOT EXISTS history_versions (year INTEGER PRIMARY KEY, revision INTEGER NOT NULL)")
            if not connection.execute("SELECT 1 FROM settings WHERE key='history_migrated'").fetchone():
                from .importer import TIME_KEYS, _lookup
                occurrences = {}
                content_occurrences = {}
                for row in connection.execute("SELECT * FROM runs ORDER BY source_path, source_row").fetchall():
                    run = dict(row)
                    run["raw"] = json.loads(run.pop("raw_json"))
                    identity = (run["source_path"], run["observed_at"], run.get("scenario") or "Unknown")
                    occurrences[identity] = occurrences.get(identity, 0) + 1
                    run["event_ordinal"] = occurrences[identity]
                    content_identity = (run["source_path"], run["row_hash"])
                    content_occurrences[content_identity] = content_occurrences.get(content_identity, 0) + 1
                    run["content_ordinal"] = content_occurrences[content_identity]
                    run["timestamp_inferred"] = not _lookup(run["raw"], TIME_KEYS) and not re.search(
                        r"(20\d{2}[.-]\d{2}[.-]\d{2})[-_ ](\d{2}[.-]\d{2}[.-]\d{2})", Path(run["source_path"]).stem)
                    self._retain_run(connection, run)
                connection.execute("INSERT INTO settings(key,value) VALUES('history_migrated','1')")
            connection.execute("""INSERT OR IGNORE INTO history_versions(year,revision)
                SELECT CAST(substr(observed_at,1,4) AS INTEGER),COUNT(*) FROM run_history GROUP BY substr(observed_at,1,4)""")

    @staticmethod
    def _retain_run(connection, run: dict[str, Any]) -> None:
        observed = datetime.fromisoformat(run["observed_at"])
        if observed.tzinfo:
            observed = observed.astimezone().replace(tzinfo=None)
        observed_text = observed.isoformat(sep=" ", timespec="seconds")
        identity = [run["source_path"], observed_text, run.get("scenario") or "Unknown", run.get("event_ordinal", 1)]
        if run.get("timestamp_inferred"):
            identity = [run["source_path"], "inferred", run["row_hash"], run.get("content_ordinal", 1)]
            previous = connection.execute("SELECT observed_at FROM run_history WHERE event_key=?", (json.dumps(identity),)).fetchone()
            if previous:
                observed_text = previous["observed_at"]
                run["observed_at"] = observed_text.replace(" ", "T")
        cursor = connection.execute("""INSERT INTO run_history(event_key,observed_at,scenario,payload_json)
            VALUES(?,?,?,?) ON CONFLICT(event_key) DO UPDATE SET payload_json=excluded.payload_json
            WHERE run_history.payload_json != excluded.payload_json""",
            (json.dumps(identity), observed_text, run.get("scenario") or "Unknown",
             json.dumps(run, ensure_ascii=False)))
        if cursor.rowcount:
            connection.execute("""INSERT INTO history_versions(year,revision) VALUES(?,1)
                ON CONFLICT(year) DO UPDATE SET revision=revision+1""", (int(observed_text[:4]),))

    def get_setting(self, key: str, default: str = "") -> str:
        """Retrieve a stored setting value by key, returning default if not set."""
        with self.connect() as connection:
            row = connection.execute("SELECT value FROM settings WHERE key = ?", (key,)).fetchone()
        return row["value"] if row else default

    def set_setting(self, key: str, value: str) -> None:
        """Insert or update a configuration key with a new value."""
        with self.connect() as connection:
            connection.execute(
                """
                INSERT INTO settings(key, value, updated_at)
                VALUES(?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = CURRENT_TIMESTAMP
                """,
                (key, value),
            )

    def upsert_source(self, path: str, size_bytes: int, mtime_ns: int, status: str, error: str | None = None) -> None:
        """Record or update a source file's metadata and ingestion status."""
        with self.connect() as connection:
            connection.execute(
                """
                INSERT INTO sources(path, size_bytes, mtime_ns, status, error)
                VALUES(?, ?, ?, ?, ?)
                ON CONFLICT(path) DO UPDATE SET
                    size_bytes = excluded.size_bytes,
                    mtime_ns = excluded.mtime_ns,
                    status = excluded.status,
                    error = excluded.error
                """,
                (path, size_bytes, mtime_ns, status, error),
            )

    def finish_source(self, path: str, size_bytes: int, mtime_ns: int, rows_seen: int) -> None:
        """Mark a source file as successfully imported with total row count and timestamp."""
        with self.connect() as connection:
            connection.execute(
                """
                UPDATE sources
                SET size_bytes = ?, mtime_ns = ?, rows_seen = ?, imported_at = CURRENT_TIMESTAMP,
                    status = 'ready', error = NULL
                WHERE path = ?
                """,
                (size_bytes, mtime_ns, rows_seen, path),
            )

    def source_signature(self, path: str) -> tuple[int, int] | None:
        """Return (size_bytes, mtime_ns) for a path to quickly check if a file changed on disk."""
        with self.connect() as connection:
            row = connection.execute("SELECT size_bytes, mtime_ns FROM sources WHERE path = ? AND status = 'ready'", (path,)).fetchone()
        if not row:
            return None
        return int(row["size_bytes"]), int(row["mtime_ns"])

    def upsert_run(self, run: dict[str, Any]) -> str:
        """Insert or update a single run idempotently based on (source_path, source_row).

        Returns:
            'unchanged' if identical row_hash already exists,
            'updated' if the row changed,
            'inserted' if this is a newly seen run.
        """
        with self.connect() as connection:
            # Check row_hash to avoid redundant writes if the parsed content is unchanged
            self._retain_run(connection, run)
            existing = connection.execute(
                "SELECT row_hash FROM runs WHERE source_path = ? AND source_row = ?",
                (run["source_path"], run["source_row"]),
            ).fetchone()
            if existing and existing["row_hash"] == run["row_hash"]:
                return "unchanged"
            connection.execute(
                """
                INSERT INTO runs(
                    source_path, source_row, row_hash, observed_at, scenario,
                    score, accuracy, duration_seconds, shots, hits, misses,
                    damage_done, damage_possible, efficiency, weapon, sensitivity,
                    sensitivity_scale, dpi, fov, fov_scale, avg_fps, resolution,
                    game_version, raw_json
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(source_path, source_row) DO UPDATE SET
                    row_hash = excluded.row_hash,
                    observed_at = excluded.observed_at,
                    imported_at = CURRENT_TIMESTAMP,
                    scenario = excluded.scenario,
                    score = excluded.score,
                    accuracy = excluded.accuracy,
                    duration_seconds = excluded.duration_seconds,
                    shots = excluded.shots,
                    hits = excluded.hits,
                    misses = excluded.misses,
                    damage_done = excluded.damage_done,
                    damage_possible = excluded.damage_possible,
                    efficiency = excluded.efficiency,
                    weapon = excluded.weapon,
                    sensitivity = excluded.sensitivity,
                    sensitivity_scale = excluded.sensitivity_scale,
                    dpi = excluded.dpi,
                    fov = excluded.fov,
                    fov_scale = excluded.fov_scale,
                    avg_fps = excluded.avg_fps,
                    resolution = excluded.resolution,
                    game_version = excluded.game_version,
                    raw_json = excluded.raw_json
                """,
                (
                    run["source_path"],
                    run["source_row"],
                    run["row_hash"],
                    run["observed_at"],
                    run.get("scenario"),
                    run.get("score"),
                    run.get("accuracy"),
                    run.get("duration_seconds"),
                    run.get("shots"),
                    run.get("hits"),
                    run.get("misses"),
                    run.get("damage_done"),
                    run.get("damage_possible"),
                    run.get("efficiency"),
                    run.get("weapon"),
                    run.get("sensitivity"),
                    run.get("sensitivity_scale"),
                    run.get("dpi"),
                    run.get("fov"),
                    run.get("fov_scale"),
                    run.get("avg_fps"),
                    run.get("resolution"),
                    run.get("game_version"),
                    json.dumps(run["raw"], ensure_ascii=False, separators=(",", ":")),
                ),
            )
        return "updated" if existing else "inserted"

    def delete_rows_after(self, source_path: str, final_row: int) -> int:
        """Prune database rows beyond final_row if a source CSV was truncated or rewritten."""
        with self.connect() as connection:
            cursor = connection.execute(
                "DELETE FROM runs WHERE source_path = ? AND source_row > ?",
                (source_path, final_row),
            )
        return cursor.rowcount

    def recent_runs(self, limit: int = 25) -> list[dict[str, Any]]:
        """Fetch the most recent runs ordered by observation time, with raw JSON deserialized."""
        limit = max(1, min(limit, 200))
        with self.connect() as connection:
            rows = connection.execute(
                """
                SELECT id, source_path, source_row, observed_at, scenario, score, accuracy,
                       duration_seconds, shots, hits, misses, damage_done, damage_possible,
                       efficiency, weapon, sensitivity, sensitivity_scale, dpi, fov,
                       fov_scale, avg_fps, resolution, game_version, raw_json, imported_at
                FROM runs
                ORDER BY observed_at DESC, id DESC
                LIMIT ?
                """,
                (limit,),
            ).fetchall()
        result = []
        for row in rows:
            item = dict(row)
            item["raw"] = json.loads(item.pop("raw_json"))
            result.append(item)
        return result

    def summary(self, days: int = 7) -> dict[str, Any]:
        """Compute rolling aggregate statistics over the past N days.

        Aggregates:
        - Total runs, unique scenarios, average and best scores.
        - True weighted accuracy (SUM(hits) / SUM(shots)) falling back to AVG(accuracy).
        - Totals for shots, hits, and misses.
        - Average FPS and details for the single latest run.
        - Top 12 most-played scenarios with their respective stats.
        """
        days = max(1, min(days, 365))
        modifier = f"-{days} days"
        with self.connect() as connection:
            # High-level totals across the rolling window
            totals = connection.execute(
                """
                SELECT
                    COUNT(*) AS runs,
                    COUNT(DISTINCT NULLIF(scenario, '')) AS scenarios,
                    AVG(score) AS average_score,
                    MAX(score) AS best_score,
                    COALESCE(SUM(hits) * 100.0 / NULLIF(SUM(shots), 0), AVG(accuracy)) AS average_accuracy,
                    SUM(shots) AS total_shots,
                    SUM(hits) AS total_hits,
                    SUM(misses) AS total_misses,
                    AVG(avg_fps) AS average_fps,
                    MAX(observed_at) AS latest_run
                FROM runs
                WHERE datetime(observed_at) >= datetime('now', ?)
                """,
                (modifier,),
            ).fetchone()
            # Scenario-level breakdown for the most-played scenarios
            top_scenarios = connection.execute(
                """
                SELECT COALESCE(NULLIF(scenario, ''), 'Unknown') AS scenario,
                       COUNT(*) AS runs, AVG(score) AS average_score, MAX(score) AS best_score,
                       COALESCE(SUM(hits) * 100.0 / NULLIF(SUM(shots), 0), AVG(accuracy)) AS average_accuracy,
                       SUM(shots) AS total_shots, SUM(hits) AS total_hits
                FROM runs
                WHERE datetime(observed_at) >= datetime('now', ?)
                GROUP BY COALESCE(NULLIF(scenario, ''), 'Unknown')
                ORDER BY runs DESC, best_score DESC
                LIMIT 12
                """,
                (modifier,),
            ).fetchall()
            # Most recently imported file info
            source = connection.execute(
                "SELECT path, imported_at, status, error, rows_seen FROM sources ORDER BY imported_at DESC LIMIT 1"
            ).fetchone()
            # Detailed stats for the most recent run
            latest = connection.execute(
                """
                SELECT observed_at, scenario, score, accuracy, duration_seconds, shots,
                       hits, misses, efficiency, weapon, sensitivity, sensitivity_scale,
                       dpi, fov, fov_scale, avg_fps, resolution, game_version
                FROM runs
                ORDER BY observed_at DESC, id DESC
                LIMIT 1
                """
            ).fetchone()
        return {
            "days": days,
            "runs": int(totals["runs"] or 0),
            "scenarios": int(totals["scenarios"] or 0),
            "average_score": totals["average_score"],
            "best_score": totals["best_score"],
            "average_accuracy": totals["average_accuracy"],
            "total_shots": totals["total_shots"],
            "total_hits": totals["total_hits"],
            "total_misses": totals["total_misses"],
            "average_fps": totals["average_fps"],
            "latest_run": totals["latest_run"],
            "latest_run_details": dict(latest) if latest else None,
            "top_scenarios": [dict(row) for row in top_scenarios],
            "latest_source": dict(source) if source else None,
        }

    def save_report(
        self,
        kind: str,
        provider: str,
        model: str,
        body: str,
        evidence: dict[str, Any],
    ) -> int:
        """Store a generated AI coaching report with the exact evidence snapshot sent to the model."""
        with self.connect() as connection:
            cursor = connection.execute(
                "INSERT INTO reports(kind, provider, model, body, evidence_json) VALUES(?, ?, ?, ?, ?)",
                (kind, provider, model, body, json.dumps(evidence, ensure_ascii=False)),
            )
        return int(cursor.lastrowid)

    def latest_report(self, kind: str) -> dict[str, Any] | None:
        """Retrieve the most recent coaching report of a given kind, or None if none generated."""
        with self.connect() as connection:
            row = connection.execute(
                """
                SELECT id, kind, provider, model, body, evidence_json, created_at
                FROM reports
                WHERE kind = ?
                ORDER BY id DESC
                LIMIT 1
                """,
                (kind,),
            ).fetchone()
        if not row:
            return None
        report = dict(row)
        report["evidence"] = json.loads(report.pop("evidence_json"))
        return report
